# see https://docs.codeclimate.com/docs/advanced-configuration#section-default-checks
version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6 # default 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 110 # default 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 7 # default 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.