version: 2

jobs:
  build:
    working_directory: /home/ubuntu/.go_workspace/src/github.com/deciphernow/gm-fabric-go
    parallelism: 1
    shell: /bin/bash --login
    environment:
      GODIST: go1.9.linux-amd64.tar.gz
      PROTOCDIST: protoc-3.3.0-linux-x86_64.zip
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Code Climate Test Reporter
        command: |
          if [ ! -f cc-test-reporter ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter; fi
    - run: mkdir -p download
    - run: test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
    - run: sudo rm -rf /usr/local/go
    - run: sudo tar -C /usr/local -xzf download/$GODIST
    - run: curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOCDIST
    - run: sudo rm -rf /usr/bin/protoc
    - run: sudo unzip $PROTOCDIST -d protoc3
    - run: sudo ln -s ${PWD}/protoc3/bin/protoc /usr/bin/protoc
    - run: sudo ln -s ${PWD}/protoc3/include/protobuf /usr/include/google/protobuf
    - run: sudo pip install docker-compose
    - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - run: sudo apt-get install -y pkg-config libssl1.0.0 libssl-dev libsasl2-dev
    - run: go get -u github.com/jteeuwen/go-bindata/...
    - run: go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    - run: go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
    - run: go get -u github.com/golang/protobuf/protoc-gen-go
    - run: go get -u github.com/armon/go-metrics
    - run: go get -u github.com/dgrijalva/jwt-go
    - run: go get -u github.com/auth0/go-jwt-middleware
    - run: go get -u github.com/gorilla/mux
    - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - run: dep init && dep ensure
    - run:
        name: Prepare Code Climate Test Reporter
        command: ./cc-test-reporter before-build
    - run: 
        name: Run the global package tests 
        command: go test $(go list ./... | grep -v '/vendor/')
    - run:
        name: Codeclimate coverage individual tests
        command: for pkg in $(go list ./... | grep -v '/vendor/'); do go test -coverprofile=cover_${pkg//\//\_}.out $pkg; done
    - run: 
        name: Convert gocov outputs to json
        command: for output in *.out; do ./cc-test-reporter format-coverage $output -t gocov --output "coverage/$output.json"; done
    - run: 
        name: Aggregate the coverage tests together
        command: ./cc-test-reporter sum-coverage coverage/*.json -o coverage/total.json
    - run: 
        name: Upload to Codeclimate
        command: ./cc-test-reporter upload-coverage -i coverage/total.json
