version: '2'

services:

  zookeeper:
    image: zookeeper
    restart: always
    expose:
      - 2181
    ports: 
      - 2181:2181
    networks:
      test-service:
        aliases:
          - zk

  test_service:
    build: ./docker
    depends_on:
      - zookeeper
    volumes:
      - ./settings.toml:/etc/fabric/settings.toml
    expose:
      - 10000
      - 10001
      - 8080
    ports:
      - 10000:10000
      - 10001:10001
      - 8080:8080
    networks:
      test-service:
        aliases:
          - test-service

networks:
  test-service: {}
