#!/bin/bash

# Copyright 2017 Decipher Technology Studios LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd `dirname $0`
openssl req -x509 -newkey rsa:4096 -keyout server.key.pem -out server.cert.pem -days 365 -nodes -subj "/C=US/OU=Decipher/CN=fabric-ssl-test-server"
openssl req -x509 -newkey rsa:4096 -keyout client.key.pem -out client.cert.pem -days 365 -nodes -subj "/C=US/OU=Decipher/CN=fabric-ssl-test-client"
openssl req -x509 -newkey rsa:4096 -keyout wrong.key.pem -out wrong.cert.pem -days 365 -nodes -subj "/C=US/OU=Decipher/CN=fabric-wrong"
cp server.cert.pem client.trust.pem
cp client.cert.pem server.trust.pem
